### PR TITLE
CCCS-23-Add-event-listener-for-event-interface

### PR DESCRIPTION
**Pull request by greenturtle537**
Migrate the event interface region to the computer screen. Add draw routines for active and inactive casing. Auto-rendered active for testing. The states do not affect the ability to click YET. Seeking PO insight.

### CODE REVIEW

**Comment by Tartarus6** [comment]
yes, disabling the option to click the screen when safe is true would be better.

**Comment by greenturtle537** [comment]
@Tartarus6 Added functionality that was requested. Please review.

**Comment by Tartarus6** [comment]
only the left side of the screen opens the popup when clicked. pls fix

**Comment by greenturtle537** [comment]
Width issue fixed in [57a71d8](https://github.com/Glitch-Technologies/Breached/pull/8/commits/57a71d85a485856130989848716b379bd969b1b2)

**Pull request merged**
