### PR TITLE
CCCS-65-Start-button-Tutorial

### PR DESCRIPTION
**Pull request by greenturtle537**
Completed the Start/Splash page for the project. Added a working demo tutorial so the user isn't completely lost. Currently unskippable at this time. Doesn't use time.

### CODE REVIEW

**Review by greenturtle537 — COMMENTED** [review]
5 smars.

**Comment by Tartarus6** [comment]
tutorial character cutout thing is broken. seems like it only alligns at one specific window size. please make them align, at least on most typical window sizes.

**Comment by greenturtle537** [comment]
@Tartarus6 Fixed for the first window. Let me know if it works on your machine so I can do the other ones.

**Comment by Tartarus6** [comment]
that fixed it, *might* want to make the boxes a bit bigger that the actual thing youre highlighting, now it sorta looks like the thing is just bright. just a suggestion, might not be worth the effort.

**Comment by greenturtle537** [comment]
Don't care. Also fixed resizing.

**Comment by Tartarus6** [comment]
some things no longer allign. the graph doesnt line up anymore, as well as the PC.

**Comment by greenturtle537** [comment]
@Tartarus6 Fixed for graph.

**Comment by greenturtle537** [comment]
Fixed the PC with the Matrix spoon trick lol.

**Comment by greenturtle537** [comment]
UTD with main. Awaiting merge.

**Comment by greenturtle537** [comment]
Pretend I looked at it. I'm tired so lets send this into main.

**Pull request merged**
